countrySelection:
    path: /country
    controller: App\Controller\CountryController::getCountry

temperatureForOneCountry:
    path: /temperature/{countryId}
    controller: App\Controller\TemperatureController::getTemperatureForOneCountry

TweetForOneCountry:
    path: /tweet/{countryId}
    controller: App\Controller\TweetController::getTweetForOneCountry